name: bmi_calculator
description: "A new Flutter that focuses on widgets customization."
publish_to: 'Google Play Store'
version: 3.9.0+21

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^11.0.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0
  firebase_storage: ^13.5.0
  firebase_data_connect: ^0.3.2
  firebase_core: ^4.14.0
  firebase_app_check: ^0.4.7
  shared_preferences: ^2.5.1
  animated_text_kit: ^4.2.3
  firebase_crashlytics: ^5.3.0
  firebase_analytics: ^12.5.0
  shimmer: ^4.0.0
  fl_chart: ^1.2.0
  intl: ^0.20.2
  sqflite_sqlcipher: ^3.4.1
  path: ^1.9.0
  connectivity_plus: ^7.3.1
  uuid: ^4.6.0
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^8.2.0
  flutter_facebook_auth: ^7.2.0
  share_plus: ^13.3.0
  otp: ^3.0.0
  flutter_web_auth_2: ^5.1.0
  flutter_secure_storage: ^10.3.1
  qr_flutter: ^4.1.0
  local_auth: ^3.0.2
  flutter_dotenv: ^6.0.1
  flutter_riverpod: ^3.4.3
  health: ^13.3.2
  flutter_local_notifications: ^22.3.0
  timezone: ^0.11.0
  flutter_timezone: ^4.1.0
  pdf: ^3.13.0
  cross_file: ^0.3.5+5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - images/logo.png
    - .env

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
