import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/bmi_record.dart';
import '../models/blood_pressure_record.dart';
import '../models/blood_sugar_record.dart';
import 'export_format.dart';

/// Generates shareable health-data exports from local records.
///
/// All methods are static and stateless — they accept data and return bytes.
/// No database, network, or platform dependencies (sharing is handled by the
/// caller via `share_plus`).
class ExportService {
  const ExportService._();

  // ── CSV ────────────────────────────────────────────────────────────────

  /// Generate a CSV string containing all health records.
  /// [anonymize] strips userId and personal details.
  static String exportCsv({
    required List<BmiRecord> bmiRecords,
    List<BloodPressureRecord> bpRecords = const [],
    List<BloodSugarRecord> glucoseRecords = const [],
    bool anonymize = false,
  }) {
    final buf = StringBuffer();
    final fmt = DateFormat('yyyy-MM-dd HH:mm');

    // BMI section
    buf.writeln('Date,Height(cm),Weight(kg),BMI,Category');
    for (final r in bmiRecords) {
      final ts = fmt.format(r.timestamp);
      buf.writeln(
          '$ts,${r.height},${r.weight},${r.bmiValue.toStringAsFixed(1)},${r.resultText}');
    }

    // BP section
    if (bpRecords.isNotEmpty) {
      buf.writeln('');
      buf.writeln('Blood Pressure');
      buf.writeln('Date,Systolic,Diastolic,Pulse,Notes');
      for (final r in bpRecords) {
        final ts = fmt.format(r.measurementTime);
        final pulse = r.pulse?.toString() ?? '';
        final notes = _sanitizeNote(r.notes, anonymize);
        buf.writeln('$ts,${r.systolic},${r.diastolic},$pulse,$notes');
      }
    }

    // Glucose section
    if (glucoseRecords.isNotEmpty) {
      buf.writeln('');
      buf.writeln('Blood Glucose');
      buf.writeln('Date,Level(mg/dL),Type,Notes');
      for (final r in glucoseRecords) {
        final ts = fmt.format(r.measurementTime);
        final notes = _sanitizeNote(r.notes, anonymize);
        buf.writeln('$ts,${r.glucoseLevel},${r.measurementType.name},$notes');
      }
    }

    return buf.toString();
  }

  // ── PDF ────────────────────────────────────────────────────────────────

  /// Generate a polished PDF report with BMI history, BP, glucose, and a
  /// summary table. Returns raw PDF bytes suitable for saving or sharing.
  static Future<Uint8List> exportPdf({
    required List<BmiRecord> bmiRecords,
    List<BloodPressureRecord> bpRecords = const [],
    List<BloodSugarRecord> glucoseRecords = const [],
    bool anonymize = false,
  }) async {
    final pdf = pw.Document();
    final fmt = DateFormat('yyyy-MM-dd');
    final dateNow = DateTime.now();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          _buildHeader(dateNow),
          pw.SizedBox(height: 16),

          // Summary cards
          _buildSummaryCards(bmiRecords, bpRecords, glucoseRecords),
          pw.SizedBox(height: 20),

          // BMI Summary
          if (bmiRecords.isNotEmpty) ...[
            _sectionTitle('BMI History'),
            pw.SizedBox(height: 6),
            _buildBmiTable(bmiRecords),
            pw.SizedBox(height: 16),
          ],

          // BP
          if (bpRecords.isNotEmpty) ...[
            _sectionTitle('Blood Pressure'),
            pw.SizedBox(height: 6),
            _buildBpTable(bpRecords),
            pw.SizedBox(height: 16),
          ],

          // Glucose
          if (glucoseRecords.isNotEmpty) ...[
            _sectionTitle('Blood Glucose'),
            pw.SizedBox(height: 6),
            _buildGlucoseTable(glucoseRecords),
          ],

          // Footer disclaimer
          pw.SizedBox(height: 24),
          pw.Align(
            alignment: pw.Alignment.center,
            child: pw.Text(
              'This report is generated by the BMI Calculator app and is not a substitute for medical advice.',
              style: const pw.TextStyle(
                fontSize: 8,
                color: PdfColors.grey600,
              ),
              textAlign: pw.TextAlign.center,
            ),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  static pw.Widget _buildHeader(DateTime generatedAt) {
    final fmt = DateFormat('yyyy-MM-dd');
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      crossAxisAlignment: pw.CrossAxisAlignment.end,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              'Health Report',
              style: pw.TextStyle(
                fontSize: 26,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.indigo,
              ),
            ),
            pw.SizedBox(height: 4),
            pw.Text(
              'Personal health data export',
              style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey600),
            ),
          ],
        ),
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
          decoration: pw.BoxDecoration(
            color: PdfColors.indigo50,
            borderRadius: pw.BorderRadius.circular(6),
          ),
          child: pw.Text(
            'Generated: ${fmt.format(generatedAt)}',
            style: pw.TextStyle(
              fontSize: 10,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.indigo,
            ),
          ),
        ),
      ],
    );
  }

  static pw.Widget _buildSummaryCards(
    List<BmiRecord> bmiRecords,
    List<BloodPressureRecord> bpRecords,
    List<BloodSugarRecord> glucoseRecords,
  ) {
    final sortedBmi = [...bmiRecords]
      ..sort((a, b) => b.timestamp.compareTo(a.timestamp));
    final latestBmi = sortedBmi.isNotEmpty ? sortedBmi.first.bmiValue : null;

    final avgBp = bpRecords.isEmpty
        ? null
        : bpRecords.map((r) => r.systolic).reduce((a, b) => a + b) / bpRecords.length;

    final avgGlucose = glucoseRecords.isEmpty
        ? null
        : glucoseRecords.map((r) => r.glucoseLevel).reduce((a, b) => a + b) /
            glucoseRecords.length;

    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
      children: [
        _summaryCard('BMI Records', '${bmiRecords.length}', 'Latest: ${_fmtOr(latestBmi)}'),
        _summaryCard('BP Records', '${bpRecords.length}', 'Avg Systolic: ${_fmtOr(avgBp)}'),
        _summaryCard(
          'Glucose Records',
          '${glucoseRecords.length}',
          'Avg: ${_fmtOr(avgGlucose)} mg/dL',
        ),
      ],
    );
  }

  static String _fmtOr(num? value) {
    if (value == null) return '—';
    return value is int ? value.toString() : value.toStringAsFixed(1);
  }

  static pw.Widget _summaryCard(String title, String count, String detail) {
    return pw.Expanded(
      child: pw.Container(
        margin: const pw.EdgeInsets.symmetric(horizontal: 4),
        padding: const pw.EdgeInsets.all(10),
        decoration: pw.BoxDecoration(
          color: PdfColors.grey100,
          borderRadius: pw.BorderRadius.circular(8),
          border: pw.Border.all(color: PdfColors.grey300),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(title,
                style: const pw.TextStyle(
                  fontSize: 9,
                  color: PdfColors.grey600,
                )),
            pw.SizedBox(height: 4),
            pw.Text(count,
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.indigo,
                )),
            pw.SizedBox(height: 2),
            pw.Text(detail,
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700)),
          ],
        ),
      ),
    );
  }

  static pw.Widget _sectionTitle(String text) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 4),
      decoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: PdfColors.indigo, width: 1.5)),
      ),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 14,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.indigo,
        ),
      ),
    );
  }

  static pw.Widget _buildBmiTable(List<BmiRecord> records) {
    final sorted = [...records]
      ..sort((a, b) => b.timestamp.compareTo(a.timestamp));
    return pw.TableHelper.fromTextArray(
      headers: ['Date', 'Height', 'Weight', 'BMI', 'Category'],
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
      cellStyle: const pw.TextStyle(fontSize: 9),
      cellAlignment: pw.Alignment.centerLeft,
      headerAlignment: pw.Alignment.centerLeft,
      data: sorted
          .map((r) => [
                DateFormat('yyyy-MM-dd').format(r.timestamp),
                '${r.height} cm',
                '${r.weight} kg',
                r.bmiValue.toStringAsFixed(1),
                r.resultText,
              ])
          .toList(),
    );
  }

  static pw.Widget _buildBpTable(List<BloodPressureRecord> records) {
    final sorted = [...records]
      ..sort((a, b) => b.measurementTime.compareTo(a.measurementTime));
    return pw.TableHelper.fromTextArray(
      headers: ['Date', 'Systolic', 'Diastolic', 'Pulse'],
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
      cellStyle: const pw.TextStyle(fontSize: 9),
      cellAlignment: pw.Alignment.centerLeft,
      headerAlignment: pw.Alignment.centerLeft,
      data: sorted
          .map((r) => [
                DateFormat('yyyy-MM-dd').format(r.measurementTime),
                '${r.systolic}',
                '${r.diastolic}',
                r.pulse?.toString() ?? '-',
              ])
          .toList(),
    );
  }

  static pw.Widget _buildGlucoseTable(List<BloodSugarRecord> records) {
    final sorted = [...records]
      ..sort((a, b) => b.measurementTime.compareTo(a.measurementTime));
    return pw.TableHelper.fromTextArray(
      headers: ['Date', 'Level (mg/dL)', 'Type'],
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
      cellStyle: const pw.TextStyle(fontSize: 9),
      cellAlignment: pw.Alignment.centerLeft,
      headerAlignment: pw.Alignment.centerLeft,
      data: sorted
          .map((r) => [
                DateFormat('yyyy-MM-dd').format(r.measurementTime),
                '${r.glucoseLevel}',
                r.measurementType.name,
              ])
          .toList(),
    );
  }

  // ── Anonymization ──────────────────────────────────────────────────────

  /// Strip personal details from records for safe sharing.
  /// Returns new records with userId replaced and personal fields removed.
  static List<BmiRecord> anonymizeBmi(List<BmiRecord> records) {
    return records
        .map((r) => BmiRecord(
              id: r.id,
              userId: 'anonymous',
              height: r.height,
              weight: r.weight,
              age: r.age,
              isMale: r.isMale,
              bmiValue: r.bmiValue,
              bmiResult: r.bmiResult,
              resultText: r.resultText,
              interpretation: r.interpretation,
              timestamp: r.timestamp,
              restingHeartRate: r.restingHeartRate,
            ))
        .toList();
  }

  static List<BloodPressureRecord> anonymizeBp(
      List<BloodPressureRecord> records) {
    return records
        .map((r) => BloodPressureRecord(
              id: r.id,
              userId: 'anonymous',
              systolic: r.systolic,
              diastolic: r.diastolic,
              pulse: r.pulse,
              measurementTime: r.measurementTime,
            ))
        .toList();
  }

  static List<BloodSugarRecord> anonymizeGlucose(
      List<BloodSugarRecord> records) {
    return records
        .map((r) => BloodSugarRecord(
              id: r.id,
              userId: 'anonymous',
              glucoseLevel: r.glucoseLevel,
              measurementType: r.measurementType,
              measurementTime: r.measurementTime,
            ))
        .toList();
  }

  static String _sanitizeNote(String? note, bool anonymize) {
    if (note == null) return '';
    if (!anonymize) return note;
    return note.replaceAll(
        RegExp(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'),
        '[redacted]');
  }
}
