// File generated by FlutterFire CLI.
// Modified to use secure configuration from environment variables.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'services/secure_config_service.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Configuration is loaded securely from environment variables to prevent
/// exposure of sensitive API keys in source code.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// import 'services/secure_config_service.dart';
/// // ...
/// await SecureConfigService.initialize();
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: SecureConfigService.firebaseApiKeyAndroid,
    appId: SecureConfigService.firebaseAppIdAndroid,
    messagingSenderId: SecureConfigService.firebaseMessagingSenderId,
    projectId: SecureConfigService.firebaseProjectId,
    databaseURL: SecureConfigService.firebaseDatabaseUrl,
    storageBucket: SecureConfigService.firebaseStorageBucket,
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: SecureConfigService.firebaseApiKeyIOS,
    appId: SecureConfigService.firebaseAppIdIOS,
    messagingSenderId: SecureConfigService.firebaseMessagingSenderId,
    projectId: SecureConfigService.firebaseProjectId,
    databaseURL: SecureConfigService.firebaseDatabaseUrl,
    storageBucket: SecureConfigService.firebaseStorageBucket,
    iosClientId: '1058678501857-s7pdncseqdfargpf0ik77a67jdlfurlj.apps.googleusercontent.com',
    iosBundleId: 'com.angerasilas.bmiCalculator',
  );

}