// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMEui8pIuqA_c6HEVHsv_Ib7VRLuJHklw',
    appId: '1:1058678501857:android:4070fd457b1589b47fa2a0',
    messagingSenderId: '1058678501857',
    projectId: 'flutterapps-db036',
    databaseURL: 'https://flutterapps-db036-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapps-db036.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARasrD9j5LktHNwmCHhYRuEsB3KKv8MIU',
    appId: '1:1058678501857:ios:8dd034c0c52893067fa2a0',
    messagingSenderId: '1058678501857',
    projectId: 'flutterapps-db036',
    databaseURL: 'https://flutterapps-db036-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapps-db036.appspot.com',
    iosClientId: '1058678501857-s7pdncseqdfargpf0ik77a67jdlfurlj.apps.googleusercontent.com',
    iosBundleId: 'com.angerasilas.bmiCalculator',
  );

}